### ISSUE TITLE
Long ways sould be split into no more than 2000-node ways

### ISSUE THREAD

**Issue by stefanb** [pnorman/ogr2osm#30]
Some wasy are too long in the source shapefile and Ogr2osm preserves that as it is. During the transformation they sould be split into no more than 2000 node part so that it would be acceptable by the OSM API. 

Pushing the limit and splitting it at exactly 2000 nodes mark might represent a problem for users when adding a new node in the way (eg a new crossing etc). This is why [OSM Inspector](http://tools.geofabrik.de/osmi/) is raising [warnings for all ways that are more than 1900 nodes long](http://wiki.openstreetmap.org/wiki/OSM_Inspector/Views/Geometry):

> Long ways with more than 1900 nodes are shown in blue. These should probably be split up into smaller parts. The OSM API allows a way to have up to 2000 nodes.

Ogr2osm should thus split at 1900 or slightly lower limit, eg 1800.

**Comment by pnorman** [comment]
If uploading a file, the importer can split at better locations than the script.

I've also generally found it better to run simplification post-conversion, which makes any way splitting at conversion useless.

**Comment by stefanb** [comment]
This wouls be handy for making the imports easier on the importers. What do you consider _better_ location of a split within the long way? Making sure splits are roughly equally long, no ridiculously short part at the end? Both such cases can be handled programatically. Something else?

Simplification post conversion where? By some other app or by the user manually (via plugin) In JOSM? Having this a automated would make it easier on the importers. 

Because of #28 simplification algorithms give strange results with duplicated shared borders of neighbouring polygons, as each polygon gets .simplified seperately. Sample can be seen below:
![image](https://cloud.githubusercontent.com/assets/319826/5688820/0fe6a750-985c-11e4-8ca3-464548440dfa.png)

**Comment by roelderickx** [comment]
Fixed in pull request #34
