### ISSUE TITLE
Converting DWG files to OSM

### ISSUE THREAD

**Issue by tawob** [pnorman/ogr2osm#37]
Hello everybody,

I am looking fro a way to convert DWG data into OSM XML format inorder to import it later in a project based on the openstreetmap-website project. According to the <a href="http://www.gdal.org/ogr_formats.html">list</a> stated on this <a href="http://wiki.openstreetmap.org/wiki/Ogr2osm">wiki-site</a>, ogr2osm should be able to consume AutoCad DWG data.

When I try to convert a DWG-file with the help of osm2ogr, I get this error:
"OGR failed to open ../path/to/myFile.dwg, format may be unsupported"

Am I missing something? Any help would be more than appreciated!

Thanks in advance!

**Comment by pnorman** [comment]
You need gdal and python-gdal supporting DWG. This might require compiling them yourself. As a first step, make sure ogrinfo can read the file.

**Comment by tawob** [comment]
Hello Paul,
thank you very much for your kind feedabck. Since I am quite a beginner in this field I would like to check if I understand what you mean
1) Additionaly to ogr2osm I have to get gdal and python gdal. As far as I know GDAL is a library.  Does python GDAL help to embed GDAL in the ogr2osm tool?
2) I have first to check if the DWG data is readable by ogrinfo, which is a further helper tool? If not it is not worth executing step 1) above. right?

Since I am absolutely rookie :-), I would appreciate very much , if there were a tutorial or may be any technical support (by you or the community)

Many thanks!

**Comment by tawob** [comment]
Hello,

I have tried to compile the gdal library with setting the flag for enabling GWD. Unfortunately I run to the error:
'dwg_headers.h:38:23: fatal error: OdaCommon.h: No such file or directory
compilation terminated.'

These are the steps that I have followed:
1) sudo apt-get install build-essential python-all-dev
2) wget http://download.osgeo.org/gdal/2.2.1/gdal-2.2.1.tar.gz
3) tar xvfz gdal-2.2.1.tar.gz
4) cd gdal-2.2.1/
5) ./configure --with-teigha=yes --with-teigha-plt=yes --with-python=yes
5) make
6) sudo make install

Furthermore, in this [site](http://www.gdal.org/drv_dwg.html) it is described how to build DWG driver. But I dont really get which paths are to update, and how this relates to the GDAL installation as decribed above.

Please help since it is urgent!

Thanks a lot in advance!

**Comment by pnorman** [comment]
I haven't built gdal with some time and haven't researched the current state of how you build DWG support. Looking at the gdal pages, recent versions might work with libopencad. These aren't ogr2osm issues, so I'm going to go ahead and close this. Maybe there's a gdal/ogr mailing list which might be better suited, or perhaps a consultant.
