### ISSUE TITLE
ImportError: No module named osgeo

### ISSUE THREAD

**Issue by toton6868** [pnorman/ogr2osm#55]
Recently I have made an update from macOS Catalina to Big Sur. My current GDAL/ogr2ogr `3.1.3` I am trying to convert a Shapefile to OSM with the following code

```
./ogr2osm.py -t translations/my_data.py -o my_data.osm -f -v --no-upload-false --never-download --never-upload --verbose data_dir/my_data.shp
```

Which is returning the following error

```
Traceback (most recent call last):
  File "./ogr2osm.py", line 51, in <module>
    from osgeo import ogr
ImportError: No module named osgeo
```

**Comment by kannes** [comment]
This is an issue of your GDAL, not of this tool.

**Comment by roelderickx** [comment]
Exactly. Please have a look where your python bindings for GDAL are installed and try to imagine what will happen when you upgrade python. I am sure you'll find the answer.
